name: AWS Login Test

on:
    push

permissions:
    id-token: write
    contents: read

jobs:
    aws-configure:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5.1.0
              with:
                aws-region: us-east-1