name: Inputs Debug

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print?:
        description: 'Print Details?'
        required: true
        default: true
        type: boolean
      details:
        description: 'The so-called details'
        required: false
        type: string
      yearBorn:
        description: 'Year Born'
        required: true
        default: 1968
        type: number
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  display-inputs:
    name: Display All Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Print All Inputs
        run: |
          echo "inputs.logLevel = ${{ inputs.logLevel }}"
          # NOTE Use of bracket notation for inputs with special characters
          echo "inputs.print? = ${{ inputs['print?'] }}"
          echo "inputs.details = ${{ inputs.details }}"
          echo "inputs.yearBorn = ${{ inputs.yearBorn }}"
          echo "inputs.environment = ${{ inputs.environment }}"
          echo "inputs values (array) = ${{ join(inputs.*, ', ') }}"
          echo "inputs raw:"
          echo "${{ toJson(inputs) }}"
  talk-to-older-people:
    runs-on: ubuntu-latest
    if: inputs.yearBorn < 2000
    steps:
      - name: Say Older Greeting
        run: echo "How does it feel to be $(( 2025 - ${{ inputs.yearBorn }}))"