name: OIDC Debug

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-debug:
    runs-on: ubuntu-latest
    steps:
      - name: OIDC Debug Info
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r
        env:
          AUDIENCE: "${{ github.server_url }}/${{ github.repository }}"